name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build-app:
    runs-on: ubuntu-latest
    defaults: 
      run:
          working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'

      - name: install dependencies
        id: install-dependencies
        run: npm ci

      - name: RUN TESTS
        id: run-tests
        run: npm run test:coverage

      - name: SonarCloud Scan
        id: run-sonar-tests
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}